package FBM.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class IDomainObject_Constraints extends BaseConstraintsDescriptor {
  public IDomainObject_Constraints() {
    super(MetaAdapterFactory.getInterfaceConcept(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a5686a2aa2L, "FBM.structure.IDomainObject"));
  }

}
