package FBM.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class IFactModelElement_Constraints extends BaseConstraintsDescriptor {
  public IFactModelElement_Constraints() {
    super(MetaAdapterFactory.getInterfaceConcept(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568f70828L, "FBM.structure.IFactModelElement"));
  }

}
