package FBM.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.openapi.intentions.IntentionExecutable;
import jetbrains.mps.openapi.intentions.Kind;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.Collections;
import jetbrains.mps.intentions.AbstractIntentionExecutable;
import FBM.behavior.DomainObjectPopulation__BehaviorDescriptor;
import jetbrains.mps.openapi.intentions.IntentionDescriptor;

public final class NewDomainObject_Intention extends AbstractIntentionDescriptor implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;
  public NewDomainObject_Intention() {
    super(Kind.NORMAL, true, new SNodePointer("r:b5b9b520-10d1-4f11-afb3-3fa6e2aae6f4(FBM.intentions)", "9079593021073150519"));
  }
  @Override
  public String getPresentation() {
    return "NewDomainObject";
  }
  @Override
  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    return true;
  }
  @Override
  public boolean isSurroundWith() {
    return false;
  }
  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new NewDomainObject_Intention.IntentionImplementation());
    }
    return myCachedExecutable;
  }
  /*package*/ final class IntentionImplementation extends AbstractIntentionExecutable {
    public IntentionImplementation() {
    }
    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "New DomainObject";
    }
    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      DomainObjectPopulation__BehaviorDescriptor.newDomainObject_id7S1crWQ8SL8.invoke(node);
    }
    @Override
    public IntentionDescriptor getDescriptor() {
      return NewDomainObject_Intention.this;
    }
  }
}
