package FBM.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import FBM.behavior.DomainObjectPopulation__BehaviorDescriptor;

public class NewDomainObject {
  public static class NodeFactory_9079593021072497468 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, SModel model) {
      {
        final SNode domainObjectPopulation = enclosingNode;
        if (SNodeOperations.isInstanceOf(domainObjectPopulation, MetaAdapterFactory.getConcept(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x7e0131bf361fd34cL, "FBM.structure.DomainObjectPopulation"))) {
          DomainObjectPopulation__BehaviorDescriptor.newDomainObject_id7S1crWQ8SL8.invoke(domainObjectPopulation);
        }
      }
    }
  }
}
