package FBM.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import FBM.behavior.FactPopulation__BehaviorDescriptor;

public class NewFact {
  public static class NodeFactory_3005699363398159785 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, SModel model) {
      {
        final SNode factPopulation = enclosingNode;
        if (SNodeOperations.isInstanceOf(factPopulation, MetaAdapterFactory.getConcept(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568f70830L, "FBM.structure.FactPopulation"))) {
          FactPopulation__BehaviorDescriptor.newFact_id2AQoUlCZ5fF.invoke(factPopulation);
        }
      }
    }
  }
}
