package FBM.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_Modality extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Modality() {
    super(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x7e0131bf35d09595L, "Modality", "r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/9079593021067007381", PrimitiveTypeId.STRING);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE__0 = new EnumerationDescriptor.MemberDescriptor(null, "alethic", "r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/9079593021067007382", "alethic");
  private final EnumerationDescriptor.MemberDescriptor VALUE__1 = new EnumerationDescriptor.MemberDescriptor(null, "deontic", "r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/9079593021067007383", "deontic");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE__0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE__0, VALUE__1);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return VALUE__0;
    }
    switch (string) {
    }
    return null;
  }
}
