package FBM.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_InstantiationMethod extends EnumerationDescriptorBase {

  public EnumerationDescriptor_InstantiationMethod() {
    super(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x7af279a9700175d3L, "InstantiationMethod", "r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/8859277185626764755", PrimitiveTypeId.STRING);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE__0 = new EnumerationDescriptor.MemberDescriptor(null, "Asserted", "r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/8859277185626764756", "Asserted");
  private final EnumerationDescriptor.MemberDescriptor VALUE__1 = new EnumerationDescriptor.MemberDescriptor(null, "Derived", "r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/8859277185626764757", "Derived");
  private final EnumerationDescriptor.MemberDescriptor VALUE__2 = new EnumerationDescriptor.MemberDescriptor(null, "Semiderived", "r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/8859277185626764760", "Semiderived");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE__0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE__0, VALUE__1, VALUE__2);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return VALUE__0;
    }
    switch (string) {
    }
    return null;
  }
}
