package FBM.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCanonicalDataValue = createDescriptorForCanonicalDataValue();
  /*package*/ final ConceptDescriptor myConceptCanonicalDataValueBoolean = createDescriptorForCanonicalDataValueBoolean();
  /*package*/ final ConceptDescriptor myConceptCanonicalDataValueInteger = createDescriptorForCanonicalDataValueInteger();
  /*package*/ final ConceptDescriptor myConceptCanonicalDataValueString = createDescriptorForCanonicalDataValueString();
  /*package*/ final ConceptDescriptor myConceptConstraint = createDescriptorForConstraint();
  /*package*/ final ConceptDescriptor myConceptConstraintName = createDescriptorForConstraintName();
  /*package*/ final ConceptDescriptor myConceptDataType = createDescriptorForDataType();
  /*package*/ final ConceptDescriptor myConceptDataValue = createDescriptorForDataValue();
  /*package*/ final ConceptDescriptor myConceptDomainObject = createDescriptorForDomainObject();
  /*package*/ final ConceptDescriptor myConceptDomainObjectPopulation = createDescriptorForDomainObjectPopulation();
  /*package*/ final ConceptDescriptor myConceptDomainObjectReference = createDescriptorForDomainObjectReference();
  /*package*/ final ConceptDescriptor myConceptDomainObjectType = createDescriptorForDomainObjectType();
  /*package*/ final ConceptDescriptor myConceptDomainValue = createDescriptorForDomainValue();
  /*package*/ final ConceptDescriptor myConceptEntityType = createDescriptorForEntityType();
  /*package*/ final ConceptDescriptor myConceptFBMEntityType = createDescriptorForFBMEntityType();
  /*package*/ final ConceptDescriptor myConceptFBMValueType = createDescriptorForFBMValueType();
  /*package*/ final ConceptDescriptor myConceptFact = createDescriptorForFact();
  /*package*/ final ConceptDescriptor myConceptFactModel = createDescriptorForFactModel();
  /*package*/ final ConceptDescriptor myConceptFactPopulation = createDescriptorForFactPopulation();
  /*package*/ final ConceptDescriptor myConceptFactRole = createDescriptorForFactRole();
  /*package*/ final ConceptDescriptor myConceptFactType = createDescriptorForFactType();
  /*package*/ final ConceptDescriptor myConceptIDomainObject = createDescriptorForIDomainObject();
  /*package*/ final ConceptDescriptor myConceptIFactModelElement = createDescriptorForIFactModelElement();
  /*package*/ final ConceptDescriptor myConceptMandatoryConstraint = createDescriptorForMandatoryConstraint();
  /*package*/ final ConceptDescriptor myConceptObjectType = createDescriptorForObjectType();
  /*package*/ final ConceptDescriptor myConceptObjectTypeName = createDescriptorForObjectTypeName();
  /*package*/ final ConceptDescriptor myConceptObjectification = createDescriptorForObjectification();
  /*package*/ final ConceptDescriptor myConceptPosition = createDescriptorForPosition();
  /*package*/ final ConceptDescriptor myConceptPredicate = createDescriptorForPredicate();
  /*package*/ final ConceptDescriptor myConceptPredicateReading = createDescriptorForPredicateReading();
  /*package*/ final ConceptDescriptor myConceptReadingRoleText = createDescriptorForReadingRoleText();
  /*package*/ final ConceptDescriptor myConceptRole = createDescriptorForRole();
  /*package*/ final ConceptDescriptor myConceptRoleReference = createDescriptorForRoleReference();
  /*package*/ final ConceptDescriptor myConceptSID = createDescriptorForSID();
  /*package*/ final ConceptDescriptor myConceptSubtyping = createDescriptorForSubtyping();
  /*package*/ final ConceptDescriptor myConceptUniquenessConstraint = createDescriptorForUniquenessConstraint();
  /*package*/ final ConceptDescriptor myConceptValueType = createDescriptorForValueType();
  /*package*/ final EnumerationDescriptor myEnumerationInstantiationMethod = new EnumerationDescriptor_InstantiationMethod();
  /*package*/ final EnumerationDescriptor myEnumerationModality = new EnumerationDescriptor_Modality();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCanonicalDataValue, myConceptCanonicalDataValueBoolean, myConceptCanonicalDataValueInteger, myConceptCanonicalDataValueString, myConceptConstraint, myConceptConstraintName, myConceptDataType, myConceptDataValue, myConceptDomainObject, myConceptDomainObjectPopulation, myConceptDomainObjectReference, myConceptDomainObjectType, myConceptDomainValue, myConceptEntityType, myConceptFBMEntityType, myConceptFBMValueType, myConceptFact, myConceptFactModel, myConceptFactPopulation, myConceptFactRole, myConceptFactType, myConceptIDomainObject, myConceptIFactModelElement, myConceptMandatoryConstraint, myConceptObjectType, myConceptObjectTypeName, myConceptObjectification, myConceptPosition, myConceptPredicate, myConceptPredicateReading, myConceptReadingRoleText, myConceptRole, myConceptRoleReference, myConceptSID, myConceptSubtyping, myConceptUniquenessConstraint, myConceptValueType);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.CanonicalDataValue:
        return myConceptCanonicalDataValue;
      case LanguageConceptSwitch.CanonicalDataValueBoolean:
        return myConceptCanonicalDataValueBoolean;
      case LanguageConceptSwitch.CanonicalDataValueInteger:
        return myConceptCanonicalDataValueInteger;
      case LanguageConceptSwitch.CanonicalDataValueString:
        return myConceptCanonicalDataValueString;
      case LanguageConceptSwitch.Constraint:
        return myConceptConstraint;
      case LanguageConceptSwitch.ConstraintName:
        return myConceptConstraintName;
      case LanguageConceptSwitch.DataType:
        return myConceptDataType;
      case LanguageConceptSwitch.DataValue:
        return myConceptDataValue;
      case LanguageConceptSwitch.DomainObject:
        return myConceptDomainObject;
      case LanguageConceptSwitch.DomainObjectPopulation:
        return myConceptDomainObjectPopulation;
      case LanguageConceptSwitch.DomainObjectReference:
        return myConceptDomainObjectReference;
      case LanguageConceptSwitch.DomainObjectType:
        return myConceptDomainObjectType;
      case LanguageConceptSwitch.DomainValue:
        return myConceptDomainValue;
      case LanguageConceptSwitch.EntityType:
        return myConceptEntityType;
      case LanguageConceptSwitch.FBMEntityType:
        return myConceptFBMEntityType;
      case LanguageConceptSwitch.FBMValueType:
        return myConceptFBMValueType;
      case LanguageConceptSwitch.Fact:
        return myConceptFact;
      case LanguageConceptSwitch.FactModel:
        return myConceptFactModel;
      case LanguageConceptSwitch.FactPopulation:
        return myConceptFactPopulation;
      case LanguageConceptSwitch.FactRole:
        return myConceptFactRole;
      case LanguageConceptSwitch.FactType:
        return myConceptFactType;
      case LanguageConceptSwitch.IDomainObject:
        return myConceptIDomainObject;
      case LanguageConceptSwitch.IFactModelElement:
        return myConceptIFactModelElement;
      case LanguageConceptSwitch.MandatoryConstraint:
        return myConceptMandatoryConstraint;
      case LanguageConceptSwitch.ObjectType:
        return myConceptObjectType;
      case LanguageConceptSwitch.ObjectTypeName:
        return myConceptObjectTypeName;
      case LanguageConceptSwitch.Objectification:
        return myConceptObjectification;
      case LanguageConceptSwitch.Position:
        return myConceptPosition;
      case LanguageConceptSwitch.Predicate:
        return myConceptPredicate;
      case LanguageConceptSwitch.PredicateReading:
        return myConceptPredicateReading;
      case LanguageConceptSwitch.ReadingRoleText:
        return myConceptReadingRoleText;
      case LanguageConceptSwitch.Role:
        return myConceptRole;
      case LanguageConceptSwitch.RoleReference:
        return myConceptRoleReference;
      case LanguageConceptSwitch.SID:
        return myConceptSID;
      case LanguageConceptSwitch.Subtyping:
        return myConceptSubtyping;
      case LanguageConceptSwitch.UniquenessConstraint:
        return myConceptUniquenessConstraint;
      case LanguageConceptSwitch.ValueType:
        return myConceptValueType;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationInstantiationMethod, myEnumerationModality);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCanonicalDataValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "CanonicalDataValue", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a5685282a6L);
    b.class_(false, true, false);
    b.super_("FBM.structure.DataValue", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a5685282a7L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3005699363387376294");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCanonicalDataValueBoolean() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "CanonicalDataValueBoolean", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568651994L);
    b.class_(false, false, false);
    b.super_("FBM.structure.CanonicalDataValue", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a5685282a6L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3005699363388594580");
    b.version(2);
    b.property("value", 0x29b663a568651995L).type(PrimitiveTypeId.BOOLEAN).origin("3005699363388594581").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCanonicalDataValueInteger() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "CanonicalDataValueInteger", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a56865198cL);
    b.class_(false, false, false);
    b.super_("FBM.structure.CanonicalDataValue", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a5685282a6L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3005699363388594572");
    b.version(2);
    b.property("value", 0x29b663a56865198dL).type(PrimitiveTypeId.INTEGER).origin("3005699363388594573").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCanonicalDataValueString() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "CanonicalDataValueString", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568651991L);
    b.class_(false, false, false);
    b.super_("FBM.structure.CanonicalDataValue", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a5685282a6L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3005699363388594577");
    b.version(2);
    b.property("value", 0x29b663a568651992L).type(PrimitiveTypeId.STRING).origin("3005699363388594578").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForConstraint() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "Constraint", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bd80212L);
    b.class_(false, true, false);
    b.super_("FBM.structure.FBMEntityType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b28L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568f70828L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778790867474");
    b.version(2);
    b.property("modality", 0x7e0131bf35d0959cL).type(MetaIdFactory.dataTypeId(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x7e0131bf35d09595L)).origin("9079593021067007388").done();
    b.aggregate("Name", 0x35ceb9094bd80215L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bd80213L).optional(true).ordered(true).multiple(false).origin("3877239778790867477").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForConstraintName() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "ConstraintName", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bd80213L);
    b.class_(false, false, false);
    b.super_("FBM.structure.FBMValueType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bd32a42L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778790867475");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "DataType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bb228e3L);
    b.class_(false, false, false);
    b.super_("FBM.structure.ObjectType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b2bL);
    b.parent(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568f70828L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778788387043");
    b.version(2);
    b.aggregate("primaryName", 0x35ceb9094bc97d3bL).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bbb571dL).optional(false).ordered(true).multiple(false).origin("3877239778789915963").done();
    b.aggregate("alternateName", 0x35ceb9094bc97d3cL).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bbb571dL).optional(true).ordered(true).multiple(false).origin("3877239778789915964").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "DataValue", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a5685282a7L);
    b.class_(false, false, false);
    b.super_("FBM.structure.FBMEntityType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b28L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3005699363387376295");
    b.version(2);
    b.associate("isOf", 0x29b663a5685282a8L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bb228e3L).optional(false).origin("3005699363387376296").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDomainObject() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "DomainObject", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568513d6bL);
    b.class_(false, false, false);
    b.super_("FBM.structure.FBMEntityType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b28L);
    b.parent(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568f70828L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3005699363387293035");
    b.version(2);
    b.associate("isInstanceOf", 0x29b663a568513d6cL).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bb228daL).optional(false).origin("3005699363387293036").done();
    b.associate("objectifiedFact", 0x7af279a96fa52273L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a5684b097bL).optional(true).origin("8859277185620714099").done();
    b.aggregate("DomainObjectSID", 0x7e0131bf363ff32bL).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568d26ac6L).optional(false).ordered(true).multiple(false).origin("9079593021074305835").done();
    b.aggregate("identifyingFact", 0x7e0131bf362d576bL).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a5684b097bL).optional(true).ordered(true).multiple(false).origin("9079593021073086315").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDomainObjectPopulation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "DomainObjectPopulation", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x7e0131bf361fd34cL);
    b.class_(false, false, false);
    b.parent(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568f70828L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/9079593021072200524");
    b.version(2);
    b.associate("objecttype", 0x7e0131bf361fd34dL).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bb228daL).optional(false).origin("9079593021072200525").done();
    b.aggregate("objects", 0x7e0131bf361fd351L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568513d6bL).optional(true).ordered(true).multiple(true).origin("9079593021072200529").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDomainObjectReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "DomainObjectReference", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a5689b73d7L);
    b.class_(false, false, false);
    b.parent(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a5686a2aa2L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3005699363392156631");
    b.version(2);
    b.associate("domainObject", 0x29b663a5689b73d8L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568513d6bL).optional(false).origin("3005699363392156632").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDomainObjectType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "DomainObjectType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bb228daL);
    b.class_(false, true, true);
    b.super_("FBM.structure.ObjectType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b2bL);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778788387034");
    b.version(2);
    b.aggregate("primaryName", 0x35ceb9094bc97d33L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bbb571dL).optional(false).ordered(true).multiple(false).origin("3877239778789915955").done();
    b.aggregate("alternateName", 0x35ceb9094bc97d35L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bbb571dL).optional(true).ordered(true).multiple(false).origin("3877239778789915957").done();
    b.aggregate("objectifies", 0x7af279a96f5d6147L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bd801aaL).optional(true).ordered(true).multiple(false).origin("8859277185616011591").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDomainValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "DomainValue", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a5685282aaL);
    b.class_(false, false, false);
    b.super_("FBM.structure.FBMEntityType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b28L);
    b.parent(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a5686a2aa2L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3005699363387376298");
    b.version(2);
    b.aggregate("has", 0x29b663a56865198aL).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a5685282a6L).optional(false).ordered(true).multiple(false).origin("3005699363388594570").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEntityType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "EntityType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bb228ddL);
    b.class_(false, false, false);
    b.super_("FBM.structure.DomainObjectType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bb228daL);
    b.parent(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568f70828L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778788387037");
    b.version(2);
    b.property("showIdentification", 0x7af279a96f63a2ccL).type(PrimitiveTypeId.BOOLEAN).origin("8859277185616421580").done();
    b.associate("directlyIdentified", 0x7e0131bf35eff733L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bd80217L).optional(true).origin("9079593021069063987").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFBMEntityType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "FBMEntityType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b28L);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778788203304");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFBMValueType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "FBMValueType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bd32a42L);
    b.class_(false, false, false);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778790550082");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFact() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "Fact", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a5684b097bL);
    b.class_(false, false, false);
    b.super_("FBM.structure.FBMEntityType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b28L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x33d23ee961a0cbf3L);
    b.parent(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568f70828L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3005699363386886523");
    b.version(2);
    b.associate("isInstanceOf", 0x29b663a5684b097cL).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b2dL).optional(false).origin("3005699363386886524").done();
    b.aggregate("factSID", 0x29b663a568d28f78L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568d26ac6L).optional(false).ordered(true).multiple(false).origin("3005699363395768184").done();
    b.aggregate("roles", 0x29b663a56853c914L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a56853c90aL).optional(true).ordered(true).multiple(true).origin("3005699363387459860").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFactModel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "FactModel", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b66L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x33d23ee961a0cbf3L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778788203366");
    b.version(2);
    b.aggregate("sysobjecttypes", 0x35ceb9094baf71bdL).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b2bL).optional(true).ordered(true).multiple(true).origin("3877239778788209085").done();
    b.aggregate("objecttypes", 0x35ceb9094be78873L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568f70828L).optional(true).ordered(true).multiple(true).origin("3877239778791884915").done();
    b.aggregate("facttypesAndConstraints", 0x35ceb9094baf5b67L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568f70828L).optional(true).ordered(true).multiple(true).origin("3877239778788203367").done();
    b.aggregate("objects", 0x29b663a56860ee4aL).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568f70828L).optional(true).ordered(true).multiple(true).origin("3005699363388321354").done();
    b.aggregate("facts", 0x29b663a5685282acL).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568f70828L).optional(true).ordered(true).multiple(true).origin("3005699363387376300").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFactPopulation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "FactPopulation", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568f70830L);
    b.class_(false, false, false);
    b.parent(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568f70828L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3005699363398158384");
    b.version(2);
    b.associate("factType", 0x29b663a568f70833L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b2dL).optional(false).origin("3005699363398158387").done();
    b.aggregate("facts", 0x29b663a568f70835L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a5684b097bL).optional(true).ordered(true).multiple(true).origin("3005699363398158389").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFactRole() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "FactRole", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a56853c90aL);
    b.class_(false, false, false);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3005699363387459850");
    b.version(2);
    b.associate("role", 0x29b663a56853c90bL).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b2cL).optional(false).origin("3005699363387459851").done();
    b.aggregate("domainObject", 0x29b663a5687473e8L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a5686a2aa2L).optional(false).ordered(true).multiple(false).origin("3005699363389600744").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFactType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "FactType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b2dL);
    b.class_(false, false, false);
    b.super_("FBM.structure.FBMEntityType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b28L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x33d23ee961a0cbf3L);
    b.parent(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568f70828L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778788203309");
    b.version(2);
    b.aggregate("Roles", 0x35ceb9094baf5b62L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b2cL).optional(true).ordered(true).multiple(true).origin("3877239778788203362").done();
    b.aggregate("Predicates", 0x35ceb9094bb58e09L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bb58e03L).optional(true).ordered(true).multiple(true).origin("3877239778788609545").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIDomainObject() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "IDomainObject", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a5686a2aa2L);
    b.interface_();
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3005699363388926626");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIFactModelElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "IFactModelElement", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568f70828L);
    b.interface_();
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3005699363398158376");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMandatoryConstraint() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "MandatoryConstraint", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x7e0131bf35d09593L);
    b.class_(false, false, false);
    b.super_("FBM.structure.Constraint", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bd80212L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/9079593021067007379");
    b.version(2);
    b.aggregate("restricts", 0x7e0131bf35d095a2L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bd8021aL).optional(true).ordered(true).multiple(true).origin("9079593021067007394").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForObjectType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "ObjectType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b2bL);
    b.class_(false, true, false);
    b.super_("FBM.structure.FBMEntityType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b28L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778788203307");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForObjectTypeName() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "ObjectTypeName", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bbb571dL);
    b.class_(false, false, false);
    b.super_("FBM.structure.FBMValueType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bd32a42L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778788988701");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForObjectification() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "Objectification", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bd801aaL);
    b.class_(false, false, false);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778790867370");
    b.version(2);
    b.associate("FactType", 0x35ceb9094bd801afL).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b2dL).optional(false).origin("3877239778790867375").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPosition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "Position", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bb58e0cL);
    b.class_(false, false, false);
    b.super_("FBM.structure.FBMEntityType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b28L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778788609548");
    b.version(2);
    b.associate("role", 0x35ceb9094bb58e11L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b2cL).optional(false).origin("3877239778788609553").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPredicate() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "Predicate", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bb58e03L);
    b.class_(false, false, false);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778788609539");
    b.version(2);
    b.aggregate("roleposition", 0x35ceb9094bb84fbeL).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bb58e0cL).optional(true).ordered(true).multiple(true).origin("3877239778788790206").done();
    b.aggregate("predicateReadings", 0x35ceb9094bb58e17L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bb84f7cL).optional(true).ordered(true).multiple(true).origin("3877239778788609559").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPredicateReading() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "PredicateReading", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bb84f7cL);
    b.class_(false, false, false);
    b.super_("FBM.structure.FBMEntityType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b28L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778788790140");
    b.version(2);
    b.property("front", 0x35ceb9094bed1885L).type(PrimitiveTypeId.STRING).origin("3877239778792249477").done();
    b.aggregate("roles", 0x35ceb9094bd50756L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bd32a44L).optional(true).ordered(true).multiple(true).origin("3877239778790672214").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReadingRoleText() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "ReadingRoleText", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bd32a44L);
    b.class_(false, false, false);
    b.super_("FBM.structure.FBMEntityType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b28L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778790550084");
    b.version(2);
    b.property("pre_bound", 0x35ceb9094bed1851L).type(PrimitiveTypeId.STRING).origin("3877239778792249425").done();
    b.property("post_bound", 0x35ceb9094bed1853L).type(PrimitiveTypeId.STRING).origin("3877239778792249427").done();
    b.property("following", 0x35ceb9094bed1856L).type(PrimitiveTypeId.STRING).origin("3877239778792249430").done();
    b.associate("role", 0x35ceb9094bd50746L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b2cL).optional(false).origin("3877239778790672198").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRole() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "Role", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b2cL);
    b.class_(false, false, false);
    b.super_("FBM.structure.FBMEntityType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b28L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778788203308");
    b.version(2);
    b.associate("objectType", 0x35ceb9094baf5b64L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b2bL).optional(false).origin("3877239778788203364").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRoleReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "RoleReference", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bd8021aL);
    b.class_(false, false, false);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778790867482");
    b.version(2);
    b.associate("role", 0x35ceb9094bd8021bL).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b2cL).optional(false).origin("3877239778790867483").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSID() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "SID", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568d26ac6L);
    b.class_(false, false, false);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3005699363395758790");
    b.version(2);
    b.property("uuid", 0x29b663a568d26ac7L).type(PrimitiveTypeId.STRING).origin("3005699363395758791").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSubtyping() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "Subtyping", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x7e0131bf35f44572L);
    b.class_(false, false, false);
    b.super_("FBM.structure.FBMEntityType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b28L);
    b.parent(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568f70828L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/9079593021069346162");
    b.version(2);
    b.associate("supertype", 0x35ceb9094bd801b9L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b2bL).optional(false).origin("3877239778790867385").done();
    b.associate("subtype", 0x35ceb9094bd801b3L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094baf5b2bL).optional(false).origin("3877239778790867379").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUniquenessConstraint() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "UniquenessConstraint", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bd80217L);
    b.class_(false, false, false);
    b.super_("FBM.structure.Constraint", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bd80212L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778790867479");
    b.version(2);
    b.aggregate("restricts", 0x35ceb9094bd80220L).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bd8021aL).optional(true).ordered(true).multiple(true).origin("3877239778790867488").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForValueType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FBM", "ValueType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bb228e0L);
    b.class_(false, false, false);
    b.super_("FBM.structure.DomainObjectType", 0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bb228daL);
    b.parent(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x29b663a568f70828L);
    b.origin("r:7472105b-d028-45fb-8323-3d9fef84b5f3(FBM.structure)/3877239778788387040");
    b.version(2);
    b.associate("mapsTo", 0x35ceb9094bbb571bL).target(0xc25c730f75b14ba8L, 0xbf0613ccd89082c9L, 0x35ceb9094bb228e3L).optional(false).origin("3877239778788988699").done();
    return b.create();
  }
}
